<?php

namespace Database\Factories;

use App\Models\Student;
use App\Models\User;
use App\Models\Batch;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Student>
 */
class StudentFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Student::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'batch_id' => Batch::factory(),
            'class' => $this->faker->optional()->word(),
            'roll' => str_pad($this->faker->numberBetween(1, 50), 3, '0', STR_PAD_LEFT),
            'section' => $this->faker->randomElement(['A', 'B', 'C', 'D']),
            'group' => $this->faker->randomElement(['Science', 'Commerce', 'Arts', 'Humanities']),
            'shift' => $this->faker->randomElement(['Morning', 'Day', 'Evening']),
            'registration_no' => null, // Will be auto-generated by model
            'name_bn' => $this->faker->optional()->name(),
            'dob' => $this->faker->optional()->date(),
            'gender' => $this->faker->optional()->randomElement(['Male', 'Female']),
            'blood_group' => $this->faker->optional()->randomElement(['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-']),
            'religion' => $this->faker->optional()->randomElement(['Islam', 'Hinduism', 'Buddhism', 'Christianity']),
            'father_name' => $this->faker->optional()->name('male'),
            'mother_name' => $this->faker->optional()->name('female'),
            'father_occupation' => $this->faker->optional()->jobTitle(),
            'mother_occupation' => $this->faker->optional()->jobTitle(),
            'father_phone' => $this->faker->optional()->phoneNumber(),
            'mother_phone' => $this->faker->optional()->phoneNumber(),
            'guardian_name' => $this->faker->optional()->name(),
            'guardian_phone' => $this->faker->optional()->phoneNumber(),
            'present_village' => $this->faker->optional()->city(),
            'present_po' => $this->faker->optional()->city(),
            'present_ps' => $this->faker->optional()->city(),
            'present_dist' => $this->faker->optional()->city(),
            'present_holding' => $this->faker->optional()->buildingNumber(),
            'permanent_village' => $this->faker->optional()->city(),
            'permanent_po' => $this->faker->optional()->city(),
            'permanent_ps' => $this->faker->optional()->city(),
            'permanent_dist' => $this->faker->optional()->city(),
            'permanent_holding' => $this->faker->optional()->buildingNumber(),
            'ssc_institute' => $this->faker->optional()->company(),
            'ssc_board' => $this->faker->optional()->word(),
            'ssc_year' => $this->faker->optional()->year(),
            'ssc_gpa' => $this->faker->optional()->randomFloat(2, 2.0, 5.0),
            'ssc_group' => $this->faker->optional()->randomElement(['Science', 'Commerce', 'Arts']),
            'hsc_institute' => $this->faker->optional()->company(),
            'hsc_board' => $this->faker->optional()->word(),
            'hsc_year' => $this->faker->optional()->year(),
            'hsc_gpa' => $this->faker->optional()->randomFloat(2, 2.0, 5.0),
            'hsc_group' => $this->faker->optional()->randomElement(['Science', 'Commerce', 'Arts']),
            'undergrad_institute' => $this->faker->optional()->company(),
            'undergrad_board' => $this->faker->optional()->word(),
            'undergrad_year' => $this->faker->optional()->year(),
            'undergrad_gpa' => $this->faker->optional()->randomFloat(2, 2.0, 4.0),
            'undergrad_group' => $this->faker->optional()->word(),
            'undergrad_department' => $this->faker->optional()->word(),
            'course_name' => $this->faker->optional()->words(3, true),
            'total_amount' => $this->faker->randomFloat(2, 5000, 50000),
            'paid_amount' => $this->faker->randomFloat(2, 0, 25000),
            'due_amount' => $this->faker->randomFloat(2, 0, 25000),
            'payment_method' => $this->faker->optional()->randomElement(['cash', 'bank', 'online']),
            'phone' => $this->faker->optional()->phoneNumber(),
            'profile_image' => $this->faker->optional()->imageUrl(200, 200, 'people'),
            'featured' => $this->faker->boolean(10),
        ];
    }

    /**
     * Indicate that the student is featured.
     */
    public function featured(): static
    {
        return $this->state(fn (array $attributes) => [
            'featured' => true,
        ]);
    }

    /**
     * Indicate that the student has dues.
     */
    public function withDues(): static
    {
        return $this->state(function (array $attributes) {
            $totalAmount = $this->faker->randomFloat(2, 10000, 50000);
            $paidAmount = $this->faker->randomFloat(2, 0, $totalAmount * 0.7);
            
            return [
                'total_amount' => $totalAmount,
                'paid_amount' => $paidAmount,
                'due_amount' => $totalAmount - $paidAmount,
            ];
        });
    }

    /**
     * Indicate that the student has no dues.
     */
    public function noDues(): static
    {
        return $this->state(function (array $attributes) {
            $totalAmount = $this->faker->randomFloat(2, 10000, 50000);
            
            return [
                'total_amount' => $totalAmount,
                'paid_amount' => $totalAmount,
                'due_amount' => 0,
            ];
        });
    }
}
